import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import FooterWrapper from "@/components/ui/FooterWrapper";

const poppins = Poppins({
  weight: ["600", "500"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.variable} antialiased`}>
        <Navbar />
        <div className="max-w-450 mx-auto">{children}</div>
        <FooterWrapper />
      </body >
    </html>
  );
}
